applications:
  - id: umami
    name: Umami
    category: Web
    description: Analytics web
    visibility: both
    internal_url: https://umami.lan/login
    external_url: https://analytics.oudard-lab.fr/
    icon: umami.svg
    order: 10

  - id: uptime-kuma
    name: Uptime Kuma
    category: Monitoring
    description: Supervision des services
    visibility: internal
    internal_url: http://192.168.1.164:3045/dashboard
    external_url:
    icon: uptime-kuma.svg
    order: 20
